### PR TITLE
10.1.5 Fix

### PR DESCRIPTION
**Pull request by Hyphie24**
Fix for 10.1.5 Merchant bug causing autoturnin from working
Updated toc to 10.1.5

### CODE REVIEW

**Comment by lure** [comment]
Hi, I removed the offending line completely as I do not remember why it was there. 
If I am proved wrong, I will revert to your suggestion.
Thank you very much for taking your time and effort.

**Comment by lure** [comment]
@Hyphie24  
I just realized that I might be missing the exact reason for the repositioning. Could you throw in a screenshot why it is important? 

Thank you so mucj for your help!

**Comment by Hyphie24** [comment]
I'm out currently, but I can post a screenshot, at least for me it caused the repair icon to be huge on the window, it could've been affected by another addon as well, but I will check when I get home this afternoon and post it.

And thank you as well

**Comment by lure** [comment]
Please, do. That would help a lot. I just can not see the issue probably because of the free trial limitations.

**Comment by Hyphie24** [comment]
image

This is just by changing the line from saying
"MerchantRepairText:SetPoint("BOTTOMLEFT", 14, 35)"
to the new line of
"MerchantRepairAllButton:SetPoint("BOTTOMLEFT", 14, 35)"

when you change the line to 
"MerchantRepairAllButton:SetPoint('BOTTOMRIGHT', MerchantFrame, 'BOTTOMLEFT', 140, 33)"

It's normal like this 
image

**Comment by lure** [comment]
what if the line is removed completely?

**Comment by Hyphie24** [comment]
if the line is comment out completely it's normal, but I don't know if it breaks another function

**Comment by lure** [comment]
I mean, I do not understand why the `MerchantRepairAllButton` is in question at all. I do not recall me changing its position...

**Comment by Hyphie24** [comment]
I think it's how that function is now, MerchantRepairText wad removed and the only thing that calls the repair button in the game files is the MerchantRepairAllButton, but when you switch 1 to 1, it causes a bug with the icons to not fit in the frame.

But if you don't need the repair button there, then that line isn't needed anymore. I'm wondering if you planned on making a repair button for that spot but never went through with it?

**Comment by lure** [comment]
https://github.com/lure/AutoTurnIn/blob/0b39d6015d5ef5d6df9b8e5e72f52df82011f04e/Merchants.lua
this is pre-patch changes, there is nothing about this button

**Comment by Hyphie24** [comment]
right MerchantRepairText on line 21 is removed. that's what breaks the auto function

**Comment by lure** [comment]
Ok, let's keep with the line removed and not add the button reposition until we learn it is necessary. 
Thank you for being with me on this!

**Comment by Hyphie24** [comment]
All good, thank you as well :D

**Pull request closed without merging**
